server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.75.129:3306/batch?autoReconnect=true
    username: root
    password: 123456

  sql:
    init:
      data-locations: classpath:org/springframework/batch/core/schema-mysql.sql
      mode: never

  batch:
    job:
      enabled: false

batch:
  save:
    path: C:\Users\phone\Desktop\TestFile\batch
mybatis:
  configuration:
    default-executor-type: batch

