#server:
#  port: 8083
#
#
#feign:
#  httpclient:
#    max-connections: 200
#    max-connections-per-route: 50
#    enabled: true
#spring:
#  cloud:
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/order
#    username: root
#    password: 123456
#
#
#seata:
#  data-source-proxy-mode: XA
#  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
#    # 参考tc服务自己的registry.conf中的配置
#    type: nacos
#    nacos: # tc
#      server-addr: localhost:8848
#      #      username: nacos
#      #      password: nacos
#      namespace: "" # 命名空间，默认public
#      group: SEATA_GROUP # 分组，默认DEFAULT_GROUP
#      application: seata-server # tc服务在nacos中的服务名称
#  tx-service-group: default_tx_group # 事务组，根据这个获取tc服务的cluster名称
#  service:
#    vgroup-mapping: # 事务组与TC服务cluster的映射关系
#      default_tx_group: default
